opencti:
  url: http://opencti:8080
  token: "CHANGE_ME"

connector:
  id: 5aa1e271-4f0a-4d4e-8d12-1c9c0ea9bde5
  type: EXTERNAL_IMPORT
  name: DEP Connector
  scope: incident,identity,indicator
  confidence: 70
  log_level: info
  interval: 3600

# Connector specific configuration
# All values can also be provided with environment variables prefixed with
# DEP_ (for example DEP_USERNAME)
# and the generic connector values with CONNECTOR_ and OPENCTI_ prefixes.
dep:
  username: your_dep_username
  password: your_dep_password
  api_key: your_dep_api_key
  client_id: ""
  login_endpoint: https://cognito-idp.eu-west-1.amazonaws.com/
  api_endpoint: https://api.eu-ep1.doubleextortion.com/v1/dbtr/privlist
  dset: ext
  lookback_days: 7
  extended_results: true
  enable_site_indicator: true
  enable_hash_indicator: true
